baseURL: "/"
languageCode: "en-uk"
title: "Greentechdev"
params:
  codeRepo: "https://github.com/greentechdev/docs"
  pageEditPath: "edit/master/content"
  siteURL: "https://greentechdev.github.io"
  author: "Naturvårdsverket - Swedish EPA"
  description: "Greentechdev is a initiative by the Swedish EPA to provide easy to use open data in the environmental domain."
enableGitInfo: true 
menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: -120
  - identifier: about
    name: About
    url: /about/
    weight: -110
  - identifier: support
    name: Support
    url: /support/
    weight: -110
markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: tango
    tabWidth: 2
outputs:
  home:
  - HTML
  - RSS
  - JSON
  page:
  - HTML
  - JSON
