baseURL: "/"
languageCode: "en-uk"
title: "GreenTechDev"
menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: -120
  - identifier: about
    name: About
    url: /about/
    weight: -110
  - identifier: support
    name: Support
    url: /support/
    weight: -110
params:
  codeRepo: "https://github.com/greentechdev/docs"
  pageEditPath: "edit/master/content"
markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: tango
    tabWidth: 2