name: Build and deploy site

on:
  push:
    branches: 
      - Master
  workflow_dispatch:

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.64.1'
          extended: true
 
      - name: Build site with hugo cli
        run: hugo -t greentech

      - name: Navigate to built public-dir
        run: cd public

      - name: Add uncommitted files
        run: git add .

      - name: Commit changes
        run: git commit -m "Rebuilding site"
                
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
